### PR TITLE
Adding max hours week

### PR DESCRIPTION
**Pull request by juanfridano**
we should merge this into master since it is the latest version

### CODE REVIEW

**Comment by pranasziaukas** [comment]
There seems to be quite a lot going on (multiple commits/changes).
While we should probably approve this to sync with the latest version running in production, makes me wonder if it is part of a migration or something else that caused this to be submitted all at once?

**Comment by gelbal** [comment]
I agree with @pranasziaukas that this PR is rather large. Is it possible to breakdown this PR into smaller ones? 

I appreciate reviewing smaller sized PRs. At its current state, it's rather intimidating to review this PR as I feel like I need to put aside 1-2 hours at least to go through everything.

**Comment by juanfridano** [comment]
All this commits have been reviewed, previous PRs have been blocked and not merged. This branch is the one in use instead of master

**Comment by gelbal** [comment]
@juanfridano sounds like you don't need a review here, right? 

Then you could self-certify this PR to merge it without any external approval.

**Comment by pranasziaukas** [comment]
What Firat said is `@balena-ci I self-certify!`

**Comment by juanfridano** [comment]
@balena-ci I self-certify!

**Pull request merged**
